### ISSUE TITLE
Discrepancy between temporal range of MERRA-2 model and ATL15 product results in IndexError

### ISSUE THREAD

**Issue by rohaizharis** [tsutterley/SMBcorr#27]
The MERRA-2 hybrid model runs until the end of 2022 but ATL15 products go until the end of 2023. As a result, the following error occurs when running the interp_SMB_ICESat2_ATL15.py function:

`IndexError: index 0 is out of bounds for axis 0 with size 0
`

**Comment by tsutterley** [comment]
Thanks for this! I think I have a fix in #29
